version: '2.1'
services:

    stuffer:
        build:
            context: ./services/webooker
            dockerfile: Dockerfile
        networks:
            - production
        ports:
            - ${HUMBLE_PORT}:8080
        environment:
            NODE_ENV: production

networks:
    production:
